plugins {
    id 'com.android.application'
}

android {
    namespace 'id.selayar.gpskamera'
    compileSdk 35

    defaultConfig {
        applicationId "id.selayar.gpskamera"
        minSdk 29
        targetSdk 35
        versionCode 4
        versionName "4.0"
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.core:core:1.16.0'

    def camerax_version = "1.6.1"
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    implementation "androidx.camera:camera-view:${camerax_version}"

    implementation 'androidx.exifinterface:exifinterface:1.4.2'
}
